import type { HomeWordSeed } from "./types";

export const homeWordSeeds: HomeWordSeed[] = [
  {
    id: "advice",
    word: "Advice",
    partOfSpeech: "Noun",
    pronunciation: "/ədˈvaɪs/",
    meaning: "A suggestion or recommendation about what someone should do.",
    examples: [
      { id: "advice-example-1", text: "She gave me good advice." },
      { id: "advice-example-2", text: "I need your advice." },
      { id: "advice-example-3", text: "Let me give you some advice." },
    ],
    note: {
      summary: "“Advice” is uncountable in English.",
      avoid: "an advice",
      use: "some advice",
    },
    difficulty: "easy",
    frequencyLabel: "Top 500",
    tags: ["communication", "daily-life"],
    status: "new",
  },
  {
    id: "by",
    word: "By",
    partOfSpeech: "Preposition",
    pronunciation: "/baɪ/",
    meaning: "Used to show who did something, how it happened, or a deadline.",
    examples: [
      { id: "by-example-1", text: "The note was written by her." },
      { id: "by-example-2", text: "Please finish it by Friday." },
      { id: "by-example-3", text: "They traveled by train." },
    ],
    note: {
      summary: "“By” often connects an action to its agent, method, or time limit.",
      avoid: "until Friday by",
      use: "by Friday",
    },
    difficulty: "easy",
    frequencyLabel: "Top 100",
    tags: ["time", "method"],
    status: "new",
  },
  {
    id: "again",
    word: "Again",
    partOfSpeech: "Adverb",
    pronunciation: "/əˈɡen/",
    meaning: "One more time, or returning to a previous state.",
    examples: [
      { id: "again-example-1", text: "Could you say that again?" },
      { id: "again-example-2", text: "The room felt quiet again." },
      { id: "again-example-3", text: "Try again tomorrow." },
    ],
    note: {
      summary: "“Again” can mean repetition or restoration.",
      avoid: "repeat again it",
      use: "repeat it again",
    },
    difficulty: "easy",
    frequencyLabel: "Top 300",
    tags: ["repetition", "daily-life"],
    status: "new",
  },
  {
    id: "context",
    word: "Context",
    partOfSpeech: "Noun",
    pronunciation: "/ˈkɑːntekst/",
    meaning: "The situation or information around something that helps explain it.",
    examples: [
      { id: "context-example-1", text: "The sentence needs more context." },
      { id: "context-example-2", text: "In this context, the word is informal." },
      { id: "context-example-3", text: "Context changes the meaning." },
    ],
    note: {
      summary: "“Context” is usually followed by “of” or “for” depending on meaning.",
      avoid: "context to this word",
      use: "context for this word",
    },
    difficulty: "medium",
    frequencyLabel: "Top 1000",
    tags: ["reading", "meaning"],
    status: "new",
  },
  {
    id: "practice",
    word: "Practice",
    partOfSpeech: "Noun",
    pronunciation: "/ˈpræktɪs/",
    meaning: "Repeated activity done to improve a skill.",
    examples: [
      { id: "practice-example-1", text: "Daily practice builds confidence." },
      { id: "practice-example-2", text: "She needs more speaking practice." },
      { id: "practice-example-3", text: "Practice makes the sentence feel natural." },
    ],
    note: {
      summary: "In American English, “practice” is both noun and verb.",
      avoid: "make practice",
      use: "do practice",
    },
    difficulty: "easy",
    frequencyLabel: "Top 700",
    tags: ["learning", "routine"],
    status: "new",
  },
  {
    id: "clear",
    word: "Clear",
    partOfSpeech: "Adjective",
    pronunciation: "/klɪr/",
    meaning: "Easy to understand, see, or hear.",
    examples: [
      { id: "clear-example-1", text: "Her explanation was clear." },
      { id: "clear-example-2", text: "The sky is clear today." },
      { id: "clear-example-3", text: "Make the instruction clear." },
    ],
    note: {
      summary: "“Clear” can describe ideas, sound, weather, or visual detail.",
      avoid: "clear to understand",
      use: "easy to understand",
    },
    difficulty: "easy",
    frequencyLabel: "Top 400",
    tags: ["clarity", "description"],
    status: "new",
  },
  {
    id: "notice",
    word: "Notice",
    partOfSpeech: "Verb",
    pronunciation: "/ˈnoʊtɪs/",
    meaning: "To become aware of something.",
    examples: [
      { id: "notice-example-1", text: "Did you notice the change?" },
      { id: "notice-example-2", text: "I noticed a small mistake." },
      { id: "notice-example-3", text: "She noticed him leaving early." },
    ],
    note: {
      summary: "“Notice” is often followed by a noun or object plus -ing.",
      avoid: "notice to something",
      use: "notice something",
    },
    difficulty: "medium",
    frequencyLabel: "Top 900",
    tags: ["attention", "observation"],
    status: "new",
  },
  {
    id: "reason",
    word: "Reason",
    partOfSpeech: "Noun",
    pronunciation: "/ˈriːzən/",
    meaning: "A cause, explanation, or justification for something.",
    examples: [
      { id: "reason-example-1", text: "There is a reason for the delay." },
      { id: "reason-example-2", text: "What is your reason?" },
      { id: "reason-example-3", text: "That reason makes sense." },
    ],
    note: {
      summary: "Use “reason for” before a noun and “reason why” before a clause.",
      avoid: "reason of the delay",
      use: "reason for the delay",
    },
    difficulty: "easy",
    frequencyLabel: "Top 250",
    tags: ["logic", "explanation"],
    status: "new",
  },
  {
    id: "improve",
    word: "Improve",
    partOfSpeech: "Verb",
    pronunciation: "/ɪmˈpruːv/",
    meaning: "To become better, or to make something better.",
    examples: [
      { id: "improve-example-1", text: "Your pronunciation will improve." },
      { id: "improve-example-2", text: "Reading helps improve vocabulary." },
      { id: "improve-example-3", text: "The app improves daily practice." },
    ],
    note: {
      summary: "“Improve” can be used with or without a direct object.",
      avoid: "improve in my English",
      use: "improve my English",
    },
    difficulty: "medium",
    frequencyLabel: "Top 800",
    tags: ["growth", "learning"],
    status: "new",
  },
  {
    id: "focus",
    word: "Focus",
    partOfSpeech: "Noun",
    pronunciation: "/ˈfoʊkəs/",
    meaning: "Careful attention given to one thing.",
    examples: [
      { id: "focus-example-1", text: "Keep your focus on the sentence." },
      { id: "focus-example-2", text: "The lesson has a clear focus." },
      { id: "focus-example-3", text: "Focus helps you remember words." },
    ],
    note: {
      summary: "As a verb, “focus” often uses “on”.",
      avoid: "focus in the word",
      use: "focus on the word",
    },
    difficulty: "easy",
    frequencyLabel: "Top 600",
    tags: ["attention", "study"],
    status: "new",
  },
];

export const currentWordSeed = homeWordSeeds[0];
