import type { HomeWordSeed } from "./types";
import type { LearningLanguage } from "../../types/settings";
import { createVocabularyWordsFromMarkdownModules } from "../markdown-words";

const markdownWordModules = import.meta.glob("../../../languages/**/*.md", {
  eager: true,
  import: "default",
  query: "?raw",
}) as Record<string, string>;

export const homeWordSeeds: HomeWordSeed[] = [
  {
    id: "advice",
    word: "Advice",
    partOfSpeech: "Noun",
    pronunciation: "/ədˈvaɪs/",
    meaning: "A suggestion or recommendation about what someone should do.",
    examples: [
      { id: "advice-example-1", text: "She gave me good advice." },
      { id: "advice-example-2", text: "I need your advice." },
      { id: "advice-example-3", text: "Let me give you some advice." },
    ],
    note: {
      summary: "“Advice” is uncountable in English.",
      avoid: "an advice",
      use: "some advice",
    },
    difficulty: "easy",
    frequencyLabel: "Top 500",
    tags: ["communication", "daily-life"],
    status: "new",
  },
  {
    id: "by",
    word: "By",
    partOfSpeech: "Preposition",
    pronunciation: "/baɪ/",
    meaning: "Used to show who did something, how it happened, or a deadline.",
    examples: [
      { id: "by-example-1", text: "The note was written by her." },
      { id: "by-example-2", text: "Please finish it by Friday." },
      { id: "by-example-3", text: "They traveled by train." },
    ],
    note: {
      summary: "“By” often connects an action to its agent, method, or time limit.",
      avoid: "until Friday by",
      use: "by Friday",
    },
    difficulty: "easy",
    frequencyLabel: "Top 100",
    tags: ["time", "method"],
    status: "new",
  },
  {
    id: "again",
    word: "Again",
    partOfSpeech: "Adverb",
    pronunciation: "/əˈɡen/",
    meaning: "One more time, or returning to a previous state.",
    examples: [
      { id: "again-example-1", text: "Could you say that again?" },
      { id: "again-example-2", text: "The room felt quiet again." },
      { id: "again-example-3", text: "Try again tomorrow." },
    ],
    note: {
      summary: "“Again” can mean repetition or restoration.",
      avoid: "repeat again it",
      use: "repeat it again",
    },
    difficulty: "easy",
    frequencyLabel: "Top 300",
    tags: ["repetition", "daily-life"],
    status: "new",
  },
  {
    id: "context",
    word: "Context",
    partOfSpeech: "Noun",
    pronunciation: "/ˈkɑːntekst/",
    meaning: "The situation or information around something that helps explain it.",
    examples: [
      { id: "context-example-1", text: "The sentence needs more context." },
      { id: "context-example-2", text: "In this context, the word is informal." },
      { id: "context-example-3", text: "Context changes the meaning." },
    ],
    note: {
      summary: "“Context” is usually followed by “of” or “for” depending on meaning.",
      avoid: "context to this word",
      use: "context for this word",
    },
    difficulty: "medium",
    frequencyLabel: "Top 1000",
    tags: ["reading", "meaning"],
    status: "new",
  },
  {
    id: "practice",
    word: "Practice",
    partOfSpeech: "Noun",
    pronunciation: "/ˈpræktɪs/",
    meaning: "Repeated activity done to improve a skill.",
    examples: [
      { id: "practice-example-1", text: "Daily practice builds confidence." },
      { id: "practice-example-2", text: "She needs more speaking practice." },
      { id: "practice-example-3", text: "Practice makes the sentence feel natural." },
    ],
    note: {
      summary: "In American English, “practice” is both noun and verb.",
      avoid: "make practice",
      use: "do practice",
    },
    difficulty: "easy",
    frequencyLabel: "Top 700",
    tags: ["learning", "routine"],
    status: "new",
  },
  {
    id: "clear",
    word: "Clear",
    partOfSpeech: "Adjective",
    pronunciation: "/klɪr/",
    meaning: "Easy to understand, see, or hear.",
    examples: [
      { id: "clear-example-1", text: "Her explanation was clear." },
      { id: "clear-example-2", text: "The sky is clear today." },
      { id: "clear-example-3", text: "Make the instruction clear." },
    ],
    note: {
      summary: "“Clear” can describe ideas, sound, weather, or visual detail.",
      avoid: "clear to understand",
      use: "easy to understand",
    },
    difficulty: "easy",
    frequencyLabel: "Top 400",
    tags: ["clarity", "description"],
    status: "new",
  },
  {
    id: "notice",
    word: "Notice",
    partOfSpeech: "Verb",
    pronunciation: "/ˈnoʊtɪs/",
    meaning: "To become aware of something.",
    examples: [
      { id: "notice-example-1", text: "Did you notice the change?" },
      { id: "notice-example-2", text: "I noticed a small mistake." },
      { id: "notice-example-3", text: "She noticed him leaving early." },
    ],
    note: {
      summary: "“Notice” is often followed by a noun or object plus -ing.",
      avoid: "notice to something",
      use: "notice something",
    },
    difficulty: "medium",
    frequencyLabel: "Top 900",
    tags: ["attention", "observation"],
    status: "new",
  },
  {
    id: "reason",
    word: "Reason",
    partOfSpeech: "Noun",
    pronunciation: "/ˈriːzən/",
    meaning: "A cause, explanation, or justification for something.",
    examples: [
      { id: "reason-example-1", text: "There is a reason for the delay." },
      { id: "reason-example-2", text: "What is your reason?" },
      { id: "reason-example-3", text: "That reason makes sense." },
    ],
    note: {
      summary: "Use “reason for” before a noun and “reason why” before a clause.",
      avoid: "reason of the delay",
      use: "reason for the delay",
    },
    difficulty: "easy",
    frequencyLabel: "Top 250",
    tags: ["logic", "explanation"],
    status: "new",
  },
  {
    id: "improve",
    word: "Improve",
    partOfSpeech: "Verb",
    pronunciation: "/ɪmˈpruːv/",
    meaning: "To become better, or to make something better.",
    examples: [
      { id: "improve-example-1", text: "Your pronunciation will improve." },
      { id: "improve-example-2", text: "Reading helps improve vocabulary." },
      { id: "improve-example-3", text: "The app improves daily practice." },
    ],
    note: {
      summary: "“Improve” can be used with or without a direct object.",
      avoid: "improve in my English",
      use: "improve my English",
    },
    difficulty: "medium",
    frequencyLabel: "Top 800",
    tags: ["growth", "learning"],
    status: "new",
  },
  {
    id: "focus",
    word: "Focus",
    partOfSpeech: "Noun",
    pronunciation: "/ˈfoʊkəs/",
    meaning: "Careful attention given to one thing.",
    examples: [
      { id: "focus-example-1", text: "Keep your focus on the sentence." },
      { id: "focus-example-2", text: "The lesson has a clear focus." },
      { id: "focus-example-3", text: "Focus helps you remember words." },
    ],
    note: {
      summary: "As a verb, “focus” often uses “on”.",
      avoid: "focus in the word",
      use: "focus on the word",
    },
    difficulty: "easy",
    frequencyLabel: "Top 600",
    tags: ["attention", "study"],
    status: "new",
  },
  {
    id: "advise",
    word: "Advise",
    partOfSpeech: "Verb",
    pronunciation: "/ədˈvaɪz/",
    meaning: "To give advice or an opinion about what someone should do.",
    examples: [
      { id: "advise-example-1", text: "The teacher advised her to read aloud." },
      { id: "advise-example-2", text: "I advise you to practice daily." },
      { id: "advise-example-3", text: "They advised caution." },
    ],
    note: {
      summary: "“Advise” is the verb; “advice” is the noun.",
      avoid: "I advice you",
      use: "I advise you",
    },
    difficulty: "medium",
    frequencyLabel: "Top 1200",
    tags: ["communication", "guidance"],
    status: "new",
  },
  {
    id: "adviser",
    word: "Adviser",
    partOfSpeech: "Noun",
    pronunciation: "/ədˈvaɪzər/",
    meaning: "A person who gives guidance or recommendations.",
    examples: [
      { id: "adviser-example-1", text: "Her adviser helped plan the course." },
      { id: "adviser-example-2", text: "Talk to an adviser before you decide." },
      { id: "adviser-example-3", text: "The adviser suggested a simpler path." },
    ],
    note: {
      summary: "“Adviser” and “advisor” are both common spellings.",
      avoid: "advice person",
      use: "adviser",
    },
    difficulty: "medium",
    frequencyLabel: "Top 1500",
    tags: ["people", "guidance"],
    status: "new",
  },
  {
    id: "advocate",
    word: "Advocate",
    partOfSpeech: "Noun",
    pronunciation: "/ˈædvəkət/",
    meaning: "A person who publicly supports an idea, person, or cause.",
    examples: [
      { id: "advocate-example-1", text: "She is an advocate for clear language." },
      { id: "advocate-example-2", text: "The group needs a strong advocate." },
      { id: "advocate-example-3", text: "He became an advocate for students." },
    ],
    note: {
      summary: "As a verb, “advocate” is pronounced differently in many accents.",
      avoid: "advocate for to learn",
      use: "advocate for learning",
    },
    difficulty: "medium",
    frequencyLabel: "Top 1300",
    tags: ["support", "people"],
    status: "new",
  },
  {
    id: "affair",
    word: "Affair",
    partOfSpeech: "Noun",
    pronunciation: "/əˈfer/",
    meaning: "An event, situation, or matter that people are involved in.",
    examples: [
      { id: "affair-example-1", text: "The meeting was a quiet affair." },
      { id: "affair-example-2", text: "It became a public affair." },
      { id: "affair-example-3", text: "The whole affair was confusing." },
    ],
    note: {
      summary: "“Affair” can mean an event, matter, or relationship depending on context.",
      avoid: "an affair public",
      use: "a public affair",
    },
    difficulty: "easy",
    frequencyLabel: "Top 1100",
    tags: ["events", "context"],
    status: "new",
  },
];

const spanishHomeWordSeeds: HomeWordSeed[] = [
  {
    id: "spanish-consejo",
    word: "Consejo",
    partOfSpeech: "Sustantivo",
    pronunciation: "/konˈsexo/",
    meaning: "Una recomendación o sugerencia sobre lo que alguien debería hacer.",
    examples: [
      { id: "spanish-consejo-example-1", text: "Ella me dio un buen consejo." },
      { id: "spanish-consejo-example-2", text: "Necesito tu consejo." },
      { id: "spanish-consejo-example-3", text: "Déjame darte un consejo." },
    ],
    note: {
      summary: "“Consejo” es contable en español.",
      avoid: "un consejo bueno me dio",
      use: "me dio un buen consejo",
    },
    difficulty: "easy",
    frequencyLabel: "Top 500",
    tags: ["comunicación", "vida-diaria"],
    status: "new",
  },
  {
    id: "spanish-por",
    word: "Por",
    partOfSpeech: "Preposición",
    pronunciation: "/poɾ/",
    meaning: "Se usa para expresar causa, medio, duración o intercambio.",
    examples: [
      { id: "spanish-por-example-1", text: "Gracias por tu ayuda." },
      { id: "spanish-por-example-2", text: "Viajamos por tren." },
      { id: "spanish-por-example-3", text: "Estudié por dos horas." },
    ],
    note: {
      summary: "“Por” suele indicar causa o medio; no siempre equivale a “para”.",
      avoid: "gracias para tu ayuda",
      use: "gracias por tu ayuda",
    },
    difficulty: "medium",
    frequencyLabel: "Top 100",
    tags: ["gramática", "uso"],
    status: "new",
  },
  {
    id: "spanish-otra-vez",
    word: "Otra vez",
    partOfSpeech: "Adverbio",
    pronunciation: "/ˈotɾa βes/",
    meaning: "Indica repetición: una vez más.",
    examples: [
      { id: "spanish-otra-vez-example-1", text: "¿Puedes repetirlo otra vez?" },
      { id: "spanish-otra-vez-example-2", text: "Lo intentaré otra vez mañana." },
      { id: "spanish-otra-vez-example-3", text: "La habitación quedó tranquila otra vez." },
    ],
    note: {
      summary: "“Otra vez” es más natural que traducir literalmente “again” en muchas frases.",
      avoid: "de nuevo vez",
      use: "otra vez",
    },
    difficulty: "easy",
    frequencyLabel: "Top 300",
    tags: ["repetición", "vida-diaria"],
    status: "new",
  },
  {
    id: "spanish-contexto",
    word: "Contexto",
    partOfSpeech: "Sustantivo",
    pronunciation: "/konˈteksto/",
    meaning: "La información o situación que ayuda a entender algo.",
    examples: [
      { id: "spanish-contexto-example-1", text: "La frase necesita más contexto." },
      { id: "spanish-contexto-example-2", text: "En este contexto, la palabra es informal." },
      { id: "spanish-contexto-example-3", text: "El contexto cambia el significado." },
    ],
    note: {
      summary: "“Contexto” suele usarse con “de” o “en”.",
      avoid: "contexto para esta frase",
      use: "contexto de esta frase",
    },
    difficulty: "medium",
    frequencyLabel: "Top 1000",
    tags: ["lectura", "significado"],
    status: "new",
  },
  {
    id: "spanish-practica",
    word: "Práctica",
    partOfSpeech: "Sustantivo",
    pronunciation: "/ˈpɾaktika/",
    meaning: "Actividad repetida para mejorar una habilidad.",
    examples: [
      { id: "spanish-practica-example-1", text: "La práctica diaria ayuda mucho." },
      { id: "spanish-practica-example-2", text: "Necesita más práctica oral." },
      { id: "spanish-practica-example-3", text: "La práctica mejora la pronunciación." },
    ],
    note: {
      summary: "“Práctica” lleva tilde cuando es sustantivo.",
      avoid: "practica diaria",
      use: "práctica diaria",
    },
    difficulty: "easy",
    frequencyLabel: "Top 700",
    tags: ["aprendizaje", "rutina"],
    status: "new",
  },
  {
    id: "spanish-claro",
    word: "Claro",
    partOfSpeech: "Adjetivo",
    pronunciation: "/ˈklaɾo/",
    meaning: "Fácil de entender, ver u oír.",
    examples: [
      { id: "spanish-claro-example-1", text: "La explicación fue clara." },
      { id: "spanish-claro-example-2", text: "El cielo está claro hoy." },
      { id: "spanish-claro-example-3", text: "Haz la instrucción más clara." },
    ],
    note: {
      summary: "“Claro” cambia a “clara” cuando acompaña un sustantivo femenino.",
      avoid: "una idea claro",
      use: "una idea clara",
    },
    difficulty: "easy",
    frequencyLabel: "Top 400",
    tags: ["claridad", "descripción"],
    status: "new",
  },
  {
    id: "spanish-notar",
    word: "Notar",
    partOfSpeech: "Verbo",
    pronunciation: "/noˈtaɾ/",
    meaning: "Darse cuenta de algo.",
    examples: [
      { id: "spanish-notar-example-1", text: "¿Notaste el cambio?" },
      { id: "spanish-notar-example-2", text: "Noté un pequeño error." },
      { id: "spanish-notar-example-3", text: "Ella notó que él salió temprano." },
    ],
    note: {
      summary: "“Notar” suele usarse con un objeto directo o una oración con “que”.",
      avoid: "notar a algo",
      use: "notar algo",
    },
    difficulty: "medium",
    frequencyLabel: "Top 900",
    tags: ["atención", "observación"],
    status: "new",
  },
  {
    id: "spanish-razon",
    word: "Razón",
    partOfSpeech: "Sustantivo",
    pronunciation: "/raˈson/",
    meaning: "Causa, explicación o motivo de algo.",
    examples: [
      { id: "spanish-razon-example-1", text: "Hay una razón para el retraso." },
      { id: "spanish-razon-example-2", text: "¿Cuál es tu razón?" },
      { id: "spanish-razon-example-3", text: "Esa razón tiene sentido." },
    ],
    note: {
      summary: "Usa “razón para” antes de un sustantivo o infinitivo.",
      avoid: "razón de estudiar",
      use: "razón para estudiar",
    },
    difficulty: "easy",
    frequencyLabel: "Top 250",
    tags: ["lógica", "explicación"],
    status: "new",
  },
  {
    id: "spanish-mejorar",
    word: "Mejorar",
    partOfSpeech: "Verbo",
    pronunciation: "/mexoˈɾaɾ/",
    meaning: "Hacer que algo sea mejor o volverse mejor.",
    examples: [
      { id: "spanish-mejorar-example-1", text: "Tu pronunciación va a mejorar." },
      { id: "spanish-mejorar-example-2", text: "Leer ayuda a mejorar el vocabulario." },
      { id: "spanish-mejorar-example-3", text: "La práctica mejora la fluidez." },
    ],
    note: {
      summary: "“Mejorar” puede usarse con o sin objeto directo.",
      avoid: "mejorar en mi español",
      use: "mejorar mi español",
    },
    difficulty: "medium",
    frequencyLabel: "Top 800",
    tags: ["crecimiento", "aprendizaje"],
    status: "new",
  },
  {
    id: "spanish-enfoque",
    word: "Enfoque",
    partOfSpeech: "Sustantivo",
    pronunciation: "/enˈfoke/",
    meaning: "Atención cuidadosa puesta en una cosa.",
    examples: [
      { id: "spanish-enfoque-example-1", text: "Mantén el enfoque en la frase." },
      { id: "spanish-enfoque-example-2", text: "La lección tiene un enfoque claro." },
      { id: "spanish-enfoque-example-3", text: "El enfoque ayuda a recordar palabras." },
    ],
    note: {
      summary: "Como verbo, “enfocarse” suele usarse con “en”.",
      avoid: "enfoque a la palabra",
      use: "enfoque en la palabra",
    },
    difficulty: "easy",
    frequencyLabel: "Top 600",
    tags: ["atención", "estudio"],
    status: "new",
  },
];

const homeWordsByLanguage: Record<LearningLanguage, HomeWordSeed[]> = {
  english: homeWordSeeds,
  spanish: spanishHomeWordSeeds,
};

export function getHomeWords(
  language: LearningLanguage,
  includeDifficultWords: boolean,
): HomeWordSeed[] {
  const markdownWords = createVocabularyWordsFromMarkdownModules(markdownWordModules, language);
  const words = markdownWords.length ? markdownWords : (homeWordsByLanguage[language] ?? homeWordSeeds);

  if (includeDifficultWords) {
    return words;
  }

  return words.filter((word) => word.status !== "difficult" && word.difficulty !== "hard");
}

export const currentWordSeed = homeWordSeeds[0];
